spring:
  profiles: DEVELOPMENT
  datasource:
    jdbc-url: jdbc:h2:mem:testdb
    username: sa
    password: password
  flyway:
    user: sa
    password: password
    url: jdbc:h2:mem:testdb
    enabled: true
    check-location: false
    locations: /db/migration/h2
  h2:
    console:
      path: /h2-console
      enabled: true
      settings:
        trace: false
        web-allow-others: false


logging.level.root: INFO
logging.level.org.springframework.web: INFO
logging.level.org.hibernate: INFO
logging.level.com.example.RestService.api: INFO
logging.level.com.example.RestService.service: INFO
